variables:
  GIT_SUBMODULE_STRATEGY: recursive


image: docker:latest
services:
  - docker:dind

stages:
  - use-models-tools

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

use-models-tools:
  stage: use-models-tools
  script:
    - export REPO_NAME=$CI_REGISTRY_IMAGE/use-models-tools
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=use-models-tools/docker/Dockerfile
    - docker build -f $DOCKER_PATH --tag latest --tag $IMAGE_NAME
#    - docker push $REPO_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME
