language: python
python:
  - "3.8"
install:
  - pip install -r use-models-tools/requirements.txt
script:
  - cd use-models-tools
  - nosetests
  - cd ../serving/translate-batch/
  - nosetests
  - cd ../translate-service/
  - nosetests
